MandarinMedien\MMCmfMenuBundle\Entity\Menu:
    type: entity
    inheritanceType: SINGLE_TABLE
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        position:
            type: integer

    oneToMany:
        items:
          targetEntity: MandarinMedien\MMCmfMenuBundle\Entity\Menu
          orderBy:
              position: ASC
          mappedBy: parent
          cascade:
              - all
          orphanRemoval: true

    manyToOne:
        parent:
            targetEntity: MandarinMedien\MMCmfMenuBundle\Entity\Menu
            inversedBy: items
            cascade:
                - all

    lifecycleCallbacks: {  }
