MandarinMedien\MMCmfMenuBundle\Entity\MenuItem:
    type: entity
    table: null
    fields:
        title:
            type: string
            length: 255

    manyToOne:
        nodeRoute:
            targetEntity: MandarinMedien\MMCmfRoutingBundle\Entity\NodeRoute
            joinColumn:
                onDelete: "SET NULL"

    lifecycleCallbacks: {  }
